// Generated by CoffeeScript 1.7.1
(function() {
  var Car;

  Car = function(model, year, miles) {
    this.model = model;
    this.year = year;
    this.miles = miles;
  };

  Car.prototype.toString = function() {
    return this.model + " has done " + this.miles + " miles";
  };

  return Car;

}).call(this);
